(function() {var implementors = {};
implementors["bit_array"] = ["impl&lt;B:&nbsp;<a class='trait' href='bit_array/trait.BitsIn.html' title='bit_array::BitsIn'>BitsIn</a> + BitBlock + <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a>,&nbsp;NBits:&nbsp;Unsigned + NonZero&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='bit_array/struct.BitArray.html' title='bit_array::BitArray'>BitArray</a>&lt;B,&nbsp;NBits&gt; <span class='where'>where NBits: <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Add.html' title='core::ops::Add'>Add</a>&lt;B::Output&gt;, NBits::Output: <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a>&lt;B1&gt;, NBits::Output::Output: <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Div.html' title='core::ops::Div'>Div</a>&lt;B::Output&gt;, NBits::Output::Output::Output: ArrayLength&lt;B&gt;</span>","impl&lt;'a,&nbsp;B:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> + 'a + <a class='trait' href='bit_array/trait.BitsIn.html' title='bit_array::BitsIn'>BitsIn</a> + BitBlock + <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a>,&nbsp;NBits:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> + 'a + Unsigned + NonZero&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='bit_array/struct.Iter.html' title='bit_array::Iter'>Iter</a>&lt;'a,&nbsp;B,&nbsp;NBits&gt; <span class='where'>where NBits: <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Add.html' title='core::ops::Add'>Add</a>&lt;B::Output&gt;, NBits::Output: <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a>&lt;B1&gt;, NBits::Output::Output: <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Div.html' title='core::ops::Div'>Div</a>&lt;B::Output&gt;, NBits::Output::Output::Output: ArrayLength&lt;B&gt;</span>","impl&lt;'a,&nbsp;B:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> + 'a&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html' title='core::clone::Clone'>Clone</a> for <a class='struct' href='bit_array/struct.Blocks.html' title='bit_array::Blocks'>Blocks</a>&lt;'a,&nbsp;B&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
